-- ============================================================
-- Hardware Management - COMPLETE MySQL Migration
-- Structure + Data from SQLite
-- Generated: 2026-03-18T01:58:17.671Z
-- ============================================================

USE `hardware`;
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;
SET SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO';

-- Drop existing tables (reverse order for FK)
DROP TABLE IF EXISTS `ribbon_consumption`;
DROP TABLE IF EXISTS `ribbons`;
DROP TABLE IF EXISTS `notifications`;
DROP TABLE IF EXISTS `activity_logs`;
DROP TABLE IF EXISTS `equipment_requests`;
DROP TABLE IF EXISTS `maintenance_schedules`;
DROP TABLE IF EXISTS `departments`;
DROP TABLE IF EXISTS `hardware_items`;
DROP TABLE IF EXISTS `categories`;

-- 1. categories
CREATE TABLE `categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `icon` VARCHAR(100) NOT NULL DEFAULT 'monitor',
  `description` VARCHAR(1000) DEFAULT '',
  `fields` LONGTEXT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_categories_name` (`name`),
  UNIQUE KEY `uk_categories_slug` (`slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 2. hardware_items
CREATE TABLE `hardware_items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT NOT NULL,
  `asset_number` VARCHAR(100) NOT NULL,
  `data` LONGTEXT NOT NULL,
  `status` VARCHAR(50) NOT NULL DEFAULT 'active',
  `condition` VARCHAR(50) NOT NULL DEFAULT 'good',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_hardware_asset_number` (`asset_number`),
  INDEX `idx_hardware_category` (`category_id`),
  INDEX `idx_hardware_status` (`status`),
  CONSTRAINT `fk_hardware_category` FOREIGN KEY (`category_id`) REFERENCES `categories`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 3. departments
CREATE TABLE `departments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_departments_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 4. maintenance_schedules
CREATE TABLE `maintenance_schedules` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hardware_id` INT DEFAULT NULL,
  `department` VARCHAR(255) DEFAULT NULL,
  `task_name` VARCHAR(500) NOT NULL,
  `reason` VARCHAR(2000) DEFAULT NULL,
  `scheduled_date` DATE NOT NULL,
  `status` VARCHAR(50) NOT NULL DEFAULT 'pending',
  `notes` VARCHAR(2000) DEFAULT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_schedules_hardware` (`hardware_id`),
  INDEX `idx_schedules_status` (`status`),
  CONSTRAINT `fk_schedules_hardware` FOREIGN KEY (`hardware_id`) REFERENCES `hardware_items`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 5. equipment_requests
CREATE TABLE `equipment_requests` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `request_number` VARCHAR(100) NOT NULL,
  `category_id` INT NOT NULL,
  `requester_name` VARCHAR(255) NOT NULL,
  `department` VARCHAR(255) DEFAULT '',
  `priority` VARCHAR(50) NOT NULL DEFAULT 'normal',
  `reason` VARCHAR(2000) DEFAULT '',
  `status` VARCHAR(50) NOT NULL DEFAULT 'pending',
  `data` LONGTEXT NOT NULL,
  `admin_notes` VARCHAR(2000) DEFAULT '',
  `quantity` INT NOT NULL DEFAULT 1,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_requests_number` (`request_number`),
  INDEX `idx_requests_status` (`status`),
  INDEX `idx_requests_category` (`category_id`),
  CONSTRAINT `fk_requests_category` FOREIGN KEY (`category_id`) REFERENCES `categories`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 6. activity_logs
CREATE TABLE `activity_logs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `action` VARCHAR(100) NOT NULL,
  `entity_type` VARCHAR(100) NOT NULL,
  `entity_id` INT DEFAULT NULL,
  `entity_name` VARCHAR(500) DEFAULT '',
  `details` LONGTEXT,
  `user_name` VARCHAR(255) DEFAULT 'System',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_activity_created` (`created_at`),
  INDEX `idx_activity_entity` (`entity_type`, `entity_id`),
  INDEX `idx_activity_action` (`action`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 7. notifications
CREATE TABLE `notifications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(100) NOT NULL,
  `title` VARCHAR(500) NOT NULL,
  `message` VARCHAR(2000) NOT NULL,
  `entity_type` VARCHAR(100) DEFAULT NULL,
  `entity_id` INT DEFAULT NULL,
  `is_read` TINYINT(1) NOT NULL DEFAULT 0,
  `priority` VARCHAR(50) NOT NULL DEFAULT 'normal',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_notifications_read` (`is_read`),
  INDEX `idx_notifications_type` (`type`),
  INDEX `idx_notifications_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 8. ribbons
CREATE TABLE `ribbons` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(500) NOT NULL,
  `ribbon_type` VARCHAR(100) NOT NULL DEFAULT 'Wax',
  `transfer_type` VARCHAR(100) NOT NULL DEFAULT 'Thermal Transfer',
  `width_mm` DECIMAL(10,2) NOT NULL DEFAULT 110.00,
  `length_m` DECIMAL(10,2) NOT NULL DEFAULT 300.00,
  `is_scratch_resistant` TINYINT(1) NOT NULL DEFAULT 0,
  `compatible_printers` LONGTEXT NOT NULL,
  `stock_quantity` INT NOT NULL DEFAULT 0,
  `min_stock` INT NOT NULL DEFAULT 5,
  `unit_price` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `supplier` VARCHAR(500) DEFAULT '',
  `notes` VARCHAR(2000) DEFAULT '',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_ribbons_type` (`ribbon_type`),
  INDEX `idx_ribbons_stock` (`stock_quantity`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 9. ribbon_consumption
CREATE TABLE `ribbon_consumption` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ribbon_id` INT NOT NULL,
  `action_type` VARCHAR(100) NOT NULL DEFAULT 'consumption',
  `quantity` INT NOT NULL DEFAULT 1,
  `printer_name` VARCHAR(500) DEFAULT '',
  `production_line` VARCHAR(255) DEFAULT '',
  `department` VARCHAR(255) DEFAULT '',
  `operator_name` VARCHAR(255) DEFAULT '',
  `notes` VARCHAR(2000) DEFAULT '',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_ribbon_consumption_ribbon` (`ribbon_id`),
  INDEX `idx_ribbon_consumption_action` (`action_type`),
  INDEX `idx_ribbon_consumption_created` (`created_at`),
  CONSTRAINT `fk_consumption_ribbon` FOREIGN KEY (`ribbon_id`) REFERENCES `ribbons`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================
-- DATA FROM SQLITE
-- ============================================================

-- categories (7 rows)
INSERT INTO `categories` (`id`, `name`, `slug`, `icon`, `description`, `fields`, `created_at`, `updated_at`) VALUES (1, 'PC / Desktop', 'pc-desktop', 'monitor', 'Komputer desktop dan workstation', '[{"key":"pc_name","label":"Device Name","type":"text","required":true},{"key":"ip_address","label":"IP Address","type":"text","required":true},{"key":"mac_address","label":"MAC Address","type":"text","required":false},{"key":"domain","label":"Work Group","type":"text","required":false},{"key":"brand","label":"Brand","type":"text","required":true},{"key":"serial_number","label":"Serial Number","type":"text","required":true},{"key":"processor","label":"Processor","type":"text","required":true},{"key":"ram_gb","label":"RAM (GB)","type":"number","required":true},{"key":"storage_type","label":"Tipe Storage","type":"select","options":["HDD","SSD","NVMe","HDD + SSD"],"required":true},{"key":"storage_capacity","label":"Kapasitas Storage","type":"text","required":true},{"key":"os_version","label":"Versi OS","type":"text","required":false},{"key":"location","label":"Lokasi","type":"text","required":true},{"key":"department","label":"Departemen","type":"text","required":true},{"key":"user_pic","label":"User / PIC","type":"text","required":true},{"key":"purchase_date","label":"Tanggal Pembelian","type":"date","required":false},{"key":"warranty_expiry","label":"Masa Garansi Berakhir","type":"date","required":false},{"key":"supplier","label":"Supplier","type":"text","required":false},{"key":"purchase_price","label":"Harga Pembelian","type":"number","required":false},{"key":"notes","label":"Catatan","type":"textarea","required":false}]', '2026-03-07 10:19:56', '2026-03-11 04:40:22');
INSERT INTO `categories` (`id`, `name`, `slug`, `icon`, `description`, `fields`, `created_at`, `updated_at`) VALUES (2, 'Laptop', 'laptop', 'laptop', 'Laptop dan notebook', '[{"key":"laptop_name","label":"Device Name","type":"text","required":true},{"key":"ip_address","label":"IP Address","type":"text","required":false},{"key":"mac_address","label":"MAC Address (LAN)","type":"text","required":false},{"key":"wifi_mac","label":"MAC Address (WiFi)","type":"text","required":false},{"key":"field_1773203737452","label":"Work Group","type":"text","required":false},{"key":"brand","label":"Brand","type":"text","required":true},{"key":"serial_number","label":"Serial Number","type":"text","required":true},{"key":"processor","label":"Processor","type":"text","required":true},{"key":"ram_gb","label":"RAM (GB)","type":"number","required":true},{"key":"storage_type","label":"Tipe Storage","type":"select","options":["HDD","SSD","NVMe","HDD + SSD"],"required":true},{"key":"storage_capacity","label":"Kapasitas Storage","type":"text","required":true},{"key":"screen_size","label":"Ukuran Layar (inch)","type":"text","required":false},{"key":"battery_health","label":"Kondisi Baterai","type":"select","options":["Baik","Cukup","Buruk","Perlu Ganti"],"required":false},{"key":"charger_included","label":"Charger Tersedia","type":"select","options":["Ya","Tidak"],"required":false},{"key":"os_version","label":"Versi OS","type":"text","required":false},{"key":"location","label":"Lokasi","type":"text","required":true},{"key":"department","label":"Departemen","type":"text","required":true},{"key":"user_pic","label":"User / PIC","type":"text","required":true},{"key":"purchase_date","label":"Tanggal Pembelian","type":"date","required":false},{"key":"warranty_expiry","label":"Masa Garansi Berakhir","type":"date","required":false},{"key":"supplier","label":"Supplier","type":"text","required":false},{"key":"purchase_price","label":"Harga Pembelian","type":"number","required":false},{"key":"notes","label":"Catatan","type":"textarea","required":false}]', '2026-03-07 10:19:56', '2026-03-11 04:41:05');
INSERT INTO `categories` (`id`, `name`, `slug`, `icon`, `description`, `fields`, `created_at`, `updated_at`) VALUES (3, 'Printer', 'printer', 'printer', 'Printer dan multifunction printer', '[{"key":"printer_name","label":"Nama Printer","type":"text","required":true},{"key":"brand","label":"Brand","type":"text","required":true},{"key":"model","label":"Model","type":"text","required":true},{"key":"serial_number","label":"Serial Number","type":"text","required":true},{"key":"printer_type","label":"Tipe Printer","type":"select","options":["Laser","Inkjet","Dot Matrix","Thermal","Label Printer"],"required":true},{"key":"connection_type","label":"Tipe Koneksi","type":"select","options":["USB","Network (LAN)","WiFi","USB + Network","Bluetooth"],"required":true},{"key":"duplex","label":"Ukuran Kertas","type":"text","options":["Ya","Tidak"],"required":false},{"key":"scan_capable","label":"Bisa Scan","type":"select","options":["Ya","Tidak"],"required":false},{"key":"toner_cartridge","label":"Toner / Cartridge","type":"text","required":false},{"key":"location","label":"Lokasi","type":"text","required":true},{"key":"floor","label":"Lantai","type":"text","required":false},{"key":"room","label":"Ruangan","type":"text","required":false},{"key":"department","label":"Departemen","type":"text","required":true},{"key":"user_pic","label":"User / PIC","type":"text","required":true},{"key":"purchase_date","label":"Tanggal Pembelian","type":"date","required":false},{"key":"warranty_expiry","label":"Masa Garansi Berakhir","type":"date","required":false},{"key":"supplier","label":"Supplier","type":"text","required":false},{"key":"purchase_price","label":"Harga Pembelian","type":"number","required":false},{"key":"notes","label":"Catatan","type":"textarea","required":false}]', '2026-03-07 10:19:56', '2026-03-11 04:46:38');
INSERT INTO `categories` (`id`, `name`, `slug`, `icon`, `description`, `fields`, `created_at`, `updated_at`) VALUES (4, 'Scanner', 'scanner', 'scan-line', 'Scanner dokumen dan gambar', '[{"key":"scanner_name","label":"Nama Scanner","type":"text","required":true},{"key":"brand","label":"Brand","type":"text","required":true},{"key":"model","label":"Model","type":"text","required":true},{"key":"serial_number","label":"Serial Number","type":"text","required":true},{"key":"scanner_type","label":"Tipe Scanner","type":"select","options":["Flatbed","ADF (Auto Document Feeder)","Handheld","Sheet-fed","Drum"],"required":true},{"key":"resolution","label":"Resolusi Maksimal (DPI)","type":"text","required":false},{"key":"connection_type","label":"Tipe Koneksi","type":"select","options":["USB","Network (LAN)","WiFi","USB + Network"],"required":true},{"key":"location","label":"Lokasi","type":"text","required":true},{"key":"floor","label":"Lantai","type":"text","required":false},{"key":"room","label":"Ruangan","type":"text","required":false},{"key":"department","label":"Departemen","type":"text","required":true},{"key":"purchase_date","label":"Tanggal Pembelian","type":"date","required":false},{"key":"warranty_expiry","label":"Masa Garansi Berakhir","type":"date","required":false},{"key":"supplier","label":"Supplier","type":"text","required":false},{"key":"purchase_price","label":"Harga Pembelian","type":"number","required":false},{"key":"notes","label":"Catatan","type":"textarea","required":false}]', '2026-03-07 10:19:56', '2026-03-11 04:47:29');
INSERT INTO `categories` (`id`, `name`, `slug`, `icon`, `description`, `fields`, `created_at`, `updated_at`) VALUES (5, 'Hub / Switch', 'hub-switch', 'network', 'Network hub dan switch', '[{"key":"device_name","label":"Nama Device","type":"text","required":true},{"key":"device_type","label":"Tipe Device","type":"select","options":["Hub","Unmanaged Switch","Managed Switch","PoE Switch","Layer 3 Switch"],"required":true},{"key":"brand","label":"Brand","type":"text","required":true},{"key":"model","label":"Model","type":"text","required":true},{"key":"serial_number","label":"Serial Number","type":"text","required":true},{"key":"total_ports","label":"Total Port","type":"number","required":true},{"key":"used_ports","label":"Port Terpakai","type":"number","required":false},{"key":"port_speed","label":"Kecepatan Port","type":"select","options":["10/100 Mbps","10/100/1000 Mbps","10 Gbps","Mixed"],"required":false},{"key":"ip_address","label":"IP Address (Management)","type":"text","required":false},{"key":"mac_address","label":"MAC Address","type":"text","required":false},{"key":"location","label":"Lokasi","type":"text","required":true},{"key":"rack_position","label":"Posisi Rak","type":"text","required":false},{"key":"floor","label":"Lantai","type":"text","required":false},{"key":"room","label":"Ruangan","type":"text","required":false},{"key":"department","label":"Departemen","type":"text","required":true},{"key":"purchase_date","label":"Tanggal Pembelian","type":"date","required":false},{"key":"warranty_expiry","label":"Masa Garansi Berakhir","type":"date","required":false},{"key":"supplier","label":"Supplier","type":"text","required":false},{"key":"purchase_price","label":"Harga Pembelian","type":"number","required":false},{"key":"notes","label":"Catatan","type":"textarea","required":false}]', '2026-03-07 10:19:56', '2026-03-11 04:44:18');
INSERT INTO `categories` (`id`, `name`, `slug`, `icon`, `description`, `fields`, `created_at`, `updated_at`) VALUES (6, 'Router', 'router', 'wifi', 'Router dan access point', '[{"key":"router_name","label":"Nama Router","type":"text","required":true},{"key":"brand","label":"Brand","type":"text","required":true},{"key":"wan_type","label":"Type","type":"select","options":["Fiber","DSL","Cable","Ethernet","4G/5G"],"required":false},{"key":"model","label":"Model","type":"text","required":true},{"key":"serial_number","label":"Serial Number","type":"text","required":true},{"key":"ip_address","label":"IP Address","type":"text","required":true},{"key":"gateway_ip","label":"Gateway IP","type":"text","required":false},{"key":"subnet_mask","label":"Subnet Mask","type":"text","required":false},{"key":"mac_address","label":"MAC Address","type":"text","required":false},{"key":"ssid","label":"SSID","type":"text","required":false},{"key":"wifi_password","label":"WiFi Password","type":"text","required":false},{"key":"location","label":"Lokasi","type":"text","required":true},{"key":"floor","label":"Lantai","type":"text","required":false},{"key":"room","label":"Ruangan","type":"text","required":false},{"key":"department","label":"Departemen","type":"text","required":true},{"key":"purchase_date","label":"Tanggal Pembelian","type":"date","required":false},{"key":"warranty_expiry","label":"Masa Garansi Berakhir","type":"date","required":false},{"key":"supplier","label":"Supplier","type":"text","required":false},{"key":"purchase_price","label":"Harga Pembelian","type":"number","required":false},{"key":"notes","label":"Catatan","type":"textarea","required":false}]', '2026-03-07 10:19:56', '2026-03-11 04:43:33');
INSERT INTO `categories` (`id`, `name`, `slug`, `icon`, `description`, `fields`, `created_at`, `updated_at`) VALUES (7, 'Monitor', 'monitor', 'tv', 'Monitor dan display', '[{"key":"brand","label":"Brand","type":"text","required":true},{"key":"model","label":"Model","type":"text","required":true},{"key":"serial_number","label":"Serial Number","type":"text","required":true},{"key":"screen_size","label":"Ukuran Layar (inch)","type":"text","required":true},{"key":"connection_ports","label":"Port Koneksi","type":"select","options":["HDMI","DisplayPort","VGA","DVI","HDMI + DP","HDMI + VGA","All"],"required":true},{"key":"connected_to","label":"Terhubung ke (Asset Number)","type":"text","required":false},{"key":"location","label":"Lokasi","type":"text","required":true},{"key":"floor","label":"Lantai","type":"text","required":false},{"key":"room","label":"Ruangan","type":"text","required":false},{"key":"department","label":"Departemen","type":"text","required":true},{"key":"user_pic","label":"User / PIC","type":"text","required":true},{"key":"purchase_date","label":"Tanggal Pembelian","type":"date","required":false},{"key":"warranty_expiry","label":"Masa Garansi Berakhir","type":"date","required":false},{"key":"supplier","label":"Supplier","type":"text","required":false},{"key":"purchase_price","label":"Harga Pembelian","type":"number","required":false},{"key":"notes","label":"Catatan","type":"textarea","required":false}]', '2026-03-07 10:19:56', '2026-03-11 04:45:17');

-- hardware_items (104 rows)
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (268, 1, 'AST-PC-PCBA-0001', '{"pc_name":"Dell","ip_address":"10.0.2.17","mac_address":"70-B5-E8-31-69-A0","brand":"Dell","serial_number":"asd","processor":"Windows 10 Pro 64-bit","ram_gb":7,"storage_type":"HDD","storage_capacity":"128 GB","os_version":"Intel(R) Core(TM) i3-9100 CPU @ 3.60GHz (4 CPUs), ~3.6GHz","location":"SMT A - L02 Input","department":"PCBA","user_pic":"L02 Input","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":"","notes":"","domain":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-14 05:06:14');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (269, 1, 'AST-PC-PCBA-0002', '{"pc_name":"HP","ip_address":"10.0.2.105","mac_address":"2C-41-38-A0-9E-04","brand":"HP","serial_number":"","processor":"Windows 10 Pro 64-bit","ram_gb":null,"storage_type":"HDD","storage_capacity":"512 GB","os_version":"Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz (4 CPUs), ~3.1GHz","location":"SMT A - L01 Input","department":"PCBA","user_pic":"L01 Input","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (270, 1, 'AST-PC-PCBA-0003', '{"pc_name":"EPSON","ip_address":"10.0.2.65","mac_address":"00:1b:fc:e6:0a:78","brand":"EPSON","serial_number":"","processor":"Linux Mint","ram_gb":null,"storage_type":"HDD","storage_capacity":"128 GB","os_version":"Intel(R) Celeron(R) CPU 420 @1.60GHz","location":"SMT A - L01 Output","department":"PCBA","user_pic":"L01 Output","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (271, 1, 'AST-PC-PCBA-0004', '{"pc_name":"EPSON","ip_address":"10.0.2.69","mac_address":"00:1d:60:2e:4d:ad","brand":"EPSON","serial_number":"","processor":"Linux Mint","ram_gb":null,"storage_type":"HDD","storage_capacity":"128 GB","os_version":"Intel(R) Celeron(R) CPU 420 @1.60GHz","location":"SMT A - L02 Output","department":"PCBA","user_pic":"L02 Output","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (272, 1, 'AST-PC-PCBA-0005', '{"pc_name":"EPSON","ip_address":"10.0.2.74","mac_address":"00:1b:fc:e6:0a:2c","brand":"EPSON","serial_number":"","processor":"Linux Mint","ram_gb":null,"storage_type":"HDD","storage_capacity":"128 GB","os_version":"Intel(R) Celeron(R) CPU 420 @1.60GHz","location":"SMT A - L03 Output","department":"PCBA","user_pic":"L03 Output","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (273, 1, 'AST-PC-PCBA-0006', '{"pc_name":"EPSON","ip_address":"192.168.100.174","mac_address":"00-1D-60-2E-08-E2","brand":"EPSON","serial_number":"","processor":"Windows 7 Professional 32-bit","ram_gb":null,"storage_type":"HDD","storage_capacity":"128 GB","os_version":"Intel(R) Celeron(R) CPU  430  @ 1.80GHz, ~1.8GHz","location":"SMT A - QC","department":"PCBA","user_pic":"QC","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (274, 1, 'AST-PC-PCBA-0007', '{"pc_name":"HP","ip_address":"10.0.2.177","mac_address":"?08-2E-5F-20-42-CB","brand":"HP","serial_number":"","processor":"Windows 10 Pro 64-bit","ram_gb":null,"storage_type":"HDD","storage_capacity":"512 GB","os_version":"Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz (4 CPUs), ~3.1GHz","location":"SMT A - L04 Output","department":"PCBA","user_pic":"L04 Output","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (275, 1, 'AST-PC-PCBA-0008', '{"pc_name":"EPSON","ip_address":"10.0.2.77","mac_address":"00-1B-FC-E4-BF-77","brand":"EPSON","serial_number":"","processor":"Windows 7 Professional 64-bit","ram_gb":null,"storage_type":"HDD","storage_capacity":"128 GB","os_version":"Intel(R) Celeron(R) D CPU 3.06GHz, ~3.1GHz","location":"SMT A - L05 Output","department":"PCBA","user_pic":"L05 Output","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (276, 1, 'AST-PC-PCBA-0009', '{"pc_name":"EPSON","ip_address":"10.0.2.20","mac_address":"00-1B-FC-E5-D4-E2","brand":"EPSON","serial_number":"","processor":"Windows 7 Professional 64-bit","ram_gb":null,"storage_type":"HDD","storage_capacity":"512 GB","os_version":"Intel(R) Celeron(R) D CPU 3.06GHz, ~3.1GHz","location":"SMT A - L06 Output","department":"PCBA","user_pic":"L06 Output","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (277, 1, 'AST-PC-PCBA-0010', '{"pc_name":"EPSON","ip_address":"192.168.1.125","mac_address":"44-F9-71-8F-53-45","brand":"EPSON","serial_number":"","processor":"Windows 10 Home 64-bit","ram_gb":null,"storage_type":"HDD","storage_capacity":"1TB","os_version":"Intel(R) Core(TM) i3-9100 CPU @ 3.60GHz (4 CPUs), ~3.6GHz","location":"SMT A - TV MONITORING","department":"PCBA","user_pic":"TV MONITORING","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (278, 1, 'AST-PC-PCBA-0011', '{"pc_name":"LENOVO","ip_address":"10.0.1.36","mac_address":"10-60-4B-60-32-CF","brand":"LENOVO","serial_number":"","processor":"Windows 11 Pro 64-bit","ram_gb":null,"storage_type":"HDD","storage_capacity":"512 GB","os_version":"Intel(R) Core(TM) i5-4590S CPU @ 3.00GHz (4 CPUs), ~3.0GHz","location":"SMT A - L07 Output","department":"PCBA","user_pic":"L07 Output","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (279, 1, 'AST-PC-PCBA-0012', '{"pc_name":"LENOVO","ip_address":"10.0.1.43","mac_address":"C8-9C-DC-27-A8-A6","brand":"LENOVO","serial_number":"","processor":"Windows 10 Enterprise 64-bit","ram_gb":null,"storage_type":"HDD","storage_capacity":"512 GB","os_version":"Intel(R) Core(TM) i5-4590S CPU @ 3.00GHz (4 CPUs), ~3.0GHz","location":"SMT A - L08 Output","department":"PCBA","user_pic":"L08 Output","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (280, 1, 'AST-PC-PCBA-0013', '{"pc_name":"Dell","ip_address":"192.168.10.5","mac_address":"00-22-15-7D-12-00","brand":"Dell","serial_number":"","processor":"Windows 11 Pro 64-bit","ram_gb":null,"storage_type":"HDD","storage_capacity":"1TB","os_version":"Intel(R) Core(TM) i5-9500 CPU @ 3.00GHz (6 CPUs), ~3.0GHz","location":"SMT A - DGS L01","department":"PCBA","user_pic":"DGS L01","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (281, 1, 'AST-PC-PCBA-0014', '{"pc_name":"Dell","ip_address":"192.168.10.80","mac_address":"64-00-6A-51-FD-19","brand":"Dell","serial_number":"","processor":"Windows 10 Home 64-bit","ram_gb":null,"storage_type":"HDD","storage_capacity":"1TB","os_version":"Intel(R) Xeon(R) E-2224G CPU @ 3.50GHz (4 CPUs), ~3.5GHz","location":"SMT A - DGS L02","department":"PCBA","user_pic":"DGS L02","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (282, 1, 'AST-PC-PCBA-0015', '{"pc_name":"Dell","ip_address":"192.168.10.79","mac_address":"44-37-E6-4A-A2-52","brand":"Dell","serial_number":"","processor":"Windows 10 Pro 64-bit","ram_gb":null,"storage_type":"HDD","storage_capacity":"512 GB","os_version":"Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 CPUs), ~3.2GHz","location":"SMT A - DGS L07","department":"PCBA","user_pic":"DGS L07","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (283, 1, 'AST-PC-PCBA-0016', '{"pc_name":"Dell","ip_address":"192.168.10.80","mac_address":"10-60-4B-5F-72-6D","brand":"Dell","serial_number":"","processor":"Windows 10 Pro 64-bit","ram_gb":null,"storage_type":"HDD","storage_capacity":"512 GB","os_version":"Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 CPUs), ~3.2GHz","location":"SMT A - DGS L08","department":"PCBA","user_pic":"DGS L08","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (284, 1, 'AST-PC-PCBA-0017', '{"pc_name":"LENOVO THINKCENTRE","ip_address":"10.0.1.93","mac_address":"70-B5-E8-2C-15-9D","brand":"LENOVO THINKCENTRE","serial_number":"","processor":"Windows 11 Pro 64-bit","ram_gb":null,"storage_type":"HDD","storage_capacity":"1TB","os_version":"Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 CPUs), ~3.2GHz","location":"SMT A - PC STAFF (KAK AYUNI)","department":"PCBA","user_pic":"PC STAFF (KAK AYUNI)","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (285, 1, 'AST-PC-PCBA-0018', '{"pc_name":"LENOVO","ip_address":"192.168.13.112","mac_address":"2C-41-38-B3-43-73","brand":"LENOVO","serial_number":"","processor":"Windows 11 Pro 64-bit","ram_gb":null,"storage_type":"HDD","storage_capacity":"256 GB","os_version":"Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz (4 CPUs), ~3.4GHz","location":"SMT A - PC STAFF (KAK FIRA)","department":"PCBA","user_pic":"PC STAFF (KAK FIRA)","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (286, 1, 'AST-PC-PCBA-0019', '{"pc_name":"Dell","ip_address":"192.168.100.165","mac_address":"FC-AA-14-D9-1E-CF","brand":"Dell","serial_number":"","processor":"Windows 11 Pro 64-bit","ram_gb":null,"storage_type":"HDD","storage_capacity":"128 GB","os_version":"Intel(R) Core(TM)2 Duo CPU E7500  @ 2.93GHz (2 CPUs), ~2.9GHz","location":"SMT A - STAFF (UNI YULI)","department":"PCBA","user_pic":"STAFF (UNI YULI)","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (287, 1, 'AST-PC-PCBA-0020', '{"pc_name":"LENOVO THINKCENTRE","ip_address":"192.168.13.51","mac_address":"C0-25-A5-A5-92-3A","brand":"LENOVO THINKCENTRE","serial_number":"","processor":"Windows 10 Pro 64-bit","ram_gb":null,"storage_type":"HDD","storage_capacity":"512 GB","os_version":"Intel(R) Pentium(R) CPU G3260 @ 3.30GHz (2 CPUs), ~3.3GHz","location":"SMT A - STAFF (BUK RIRIN)","department":"PCBA","user_pic":"STAFF (BUK RIRIN)","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (288, 1, 'AST-PC-PCBA-0021', '{"pc_name":"Dell","ip_address":"10.0.2.178","mac_address":"C0-25-A5-9B-7B-50","brand":"Dell","serial_number":"","processor":"Windows 11 Home 64-bit","ram_gb":null,"storage_type":"HDD","storage_capacity":"512 GB","os_version":"Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz (4 CPUs), ~3.1GHz","location":"SMT A - PC STAFF","department":"PCBA","user_pic":"PC STAFF","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (289, 1, 'AST-PC-PCBA-0022', '{"pc_name":"Acer","ip_address":"192.168.100.143","mac_address":"?70-B5-E8-7A-D8-1D","brand":"Acer","serial_number":"","processor":"Windows 10 Pro 64-bit","ram_gb":null,"storage_type":"HDD","storage_capacity":"128 GB","os_version":"Intel(R)Core(TM)i3-4130CPU @3.40GHz(4 CPUs),~3.4GHz","location":"SMT A - STAFF (BG REZA, REGI)","department":"PCBA","user_pic":"STAFF (BG REZA, REGI)","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (290, 1, 'AST-PC-PCBA-0023', '{"pc_name":"LENOVO THINKCENTRE","ip_address":"10.0.2.44","mac_address":"C0-25-A5-9C-8F-01","brand":"LENOVO THINKCENTRE","serial_number":"","processor":"Windows 11 Pro 64-bit","ram_gb":null,"storage_type":"HDD","storage_capacity":"128 GB","os_version":"Intel(R) Pentium(R) CPU G4400 @ 3.30GHz (2 CPUs), ~3.3GHz","location":"SMT A - PC ESD","department":"PCBA","user_pic":"PC ESD","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (291, 1, 'AST-PC-PCBA-0024', '{"pc_name":"Dell","ip_address":"10.0.1.56","mac_address":"?E0-BE-03-2D-BA-97","brand":"Dell","serial_number":"","processor":"Windows 7 Professional 64-bit","ram_gb":null,"storage_type":"HDD","storage_capacity":"","os_version":"ntel(R) Core(TM)2 Duo CPU     E7500  @ 2.93GHz (2 CPUs), ~2.9GHz","location":"SMT A - TECHNICIAN","department":"PCBA","user_pic":"TECHNICIAN","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (292, 1, 'AST-PC-PCBA-0025', '{"pc_name":"HP","ip_address":"10.0.2.190","mac_address":"?E0-BE-03-26-51-5B","brand":"HP","serial_number":"","processor":"Windows 11 Home 64-bit","ram_gb":null,"storage_type":"HDD","storage_capacity":"512 GB","os_version":"Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz (4 CPUs), ~3.1GHz","location":"SMT B - L12 Input","department":"PCBA","user_pic":"L12 Input","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (293, 1, 'AST-PC-PCBA-0026', '{"pc_name":"EPSON","ip_address":"10.0.2.87","mac_address":"C0-25-A5-A4-79-40","brand":"EPSON","serial_number":"","processor":"Windows 10 Pro 64-bit","ram_gb":null,"storage_type":"HDD","storage_capacity":"128 GB","os_version":"Intel(R) Celeron(R) CPU          420  @ 1.60GHz, ~1.6GHz","location":"SMT B - L13 Input","department":"PCBA","user_pic":"L13 Input","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (294, 1, 'AST-PC-PCBA-0027', '{"pc_name":"EPSON","ip_address":"10.0.2.84","mac_address":"E4-54-E8-D3-D0-B8","brand":"EPSON","serial_number":"","processor":"Windows 7 Professional 64-bit","ram_gb":null,"storage_type":"HDD","storage_capacity":"128 GB","os_version":"Intel(R) Celeron(R) CPU          430  @ 1.80GHz, ~1.8GHz","location":"SMT B - L15 Input","department":"PCBA","user_pic":"L15 Input","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (295, 1, 'AST-PC-PCBA-0028', '{"pc_name":"Dell","ip_address":"10.0.2.29","mac_address":"20-88-10-5C-ED-B0","brand":"Dell","serial_number":"","processor":"Windows 7 Professional 32-bit","ram_gb":null,"storage_type":"HDD","storage_capacity":"1 TB","os_version":"Intel(R) Core(TM) i3-9100 CPU @ 3.60GHz (4 CPUs), ~3.6GHz","location":"SMT B - L16 Input","department":"PCBA","user_pic":"L16 Input","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (296, 1, 'AST-PC-PCBA-0029', '{"pc_name":"Dell","ip_address":"192.168.13.97","mac_address":"44-F9-71-7D-0B-96","brand":"Dell","serial_number":"","processor":"Windows 10 Home 64-bit","ram_gb":null,"storage_type":"HDD","storage_capacity":"512 GB","os_version":"Intel(R) Celeron(R) CPU          430  @ 1.80GHz, ~1.8GHz","location":"SMT B - L17 Input","department":"PCBA","user_pic":"L17 Input","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (297, 1, 'AST-PC-PCBA-0030', '{"pc_name":"EPSON","ip_address":"10.0.2.79","mac_address":"44-F9-71-7C-EE-CD","brand":"EPSON","serial_number":"","processor":"Windows 7 Professional 32-bit","ram_gb":null,"storage_type":"HDD","storage_capacity":"256GB","os_version":"Intel(R) Celeron(R) CPU 420 @1.60GHz","location":"SMT B - L12 Output","department":"PCBA","user_pic":"L12 Output","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (298, 1, 'AST-PC-PCBA-0031', '{"pc_name":"EPSON","ip_address":"10.0.2.94","mac_address":"18-03-73-E7-1B-7A","brand":"EPSON","serial_number":"","processor":"Windows 7 Professional 32-bit","ram_gb":null,"storage_type":"HDD","storage_capacity":"","os_version":"Intel(R) Celeron(R) CPU          430  @ 1.80GHz, ~1.8GHz","location":"SMT B - L13 Output","department":"PCBA","user_pic":"L13 Output","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (299, 1, 'AST-PC-PCBA-0032', '{"pc_name":"EPSON","ip_address":"10.0.2.82","mac_address":"E4-54-E8-DA-DC-F4","brand":"EPSON","serial_number":"","processor":"Windows 7 Ultimate 32-bit","ram_gb":null,"storage_type":"HDD","storage_capacity":"","os_version":"Intel(R) Celeron(R) CPU          430  @ 1.80GHz, ~1.8GHz","location":"SMT B - L15 Output","department":"PCBA","user_pic":"L15 Output","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (300, 1, 'AST-PC-PCBA-0033', '{"pc_name":"Dell","ip_address":"10.0.2.205","mac_address":"?00-1B-FC-E5-3B-7B","brand":"Dell","serial_number":"","processor":"Windows 10 Pro 64-bit","ram_gb":null,"storage_type":"HDD","storage_capacity":"480GB","os_version":"Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 CPUs), ~3.2GHz","location":"SMT B - L16 Output","department":"PCBA","user_pic":"L16 Output","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (301, 1, 'AST-PC-PCBA-0034', '{"pc_name":"LENOVO","ip_address":"192.168.10.8","mac_address":"E4-54-E8-D9-51-7F","brand":"LENOVO","serial_number":"","processor":"Windows 10 Pro 64-bit","ram_gb":null,"storage_type":"HDD","storage_capacity":"1TB","os_version":"Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 CPUs), ~3.2GHz","location":"DGS - L12","department":"PCBA","user_pic":"DGS - L12","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (302, 1, 'AST-PC-PCBA-0035', '{"pc_name":"ASUS","ip_address":"192.168.10.6","mac_address":"6C-4B-90-5E-E1-04","brand":"ASUS","serial_number":"","processor":"Windows 10 Home 64-bit","ram_gb":null,"storage_type":"HDD","storage_capacity":"1TB","os_version":"Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 CPUs), ~3.2GHz","location":"DGS - L16","department":"PCBA","user_pic":"DGS - L16","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (303, 1, 'AST-PC-PCBA-0036', '{"pc_name":"ASUS","ip_address":"192.168.10.7","mac_address":"?00-26-18-32-D3-61","brand":"ASUS","serial_number":"","processor":"Windows 7 Professional 32-bit","ram_gb":null,"storage_type":"HDD","storage_capacity":"1TB","os_version":"Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 CPUs), ~3.2GHz","location":"DGS - L17","department":"PCBA","user_pic":"DGS - L17","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (304, 1, 'AST-PC-PCBA-0037', '{"pc_name":"LENOVO","ip_address":"10.0.2.60","mac_address":"00-25-64-9A-4F-13","brand":"LENOVO","serial_number":"","processor":"Windows 7 Professional 32-bit","ram_gb":null,"storage_type":"HDD","storage_capacity":"512GB","os_version":"Intel(R) Core(TM) i5- CPU  750@ 2.67GHz (4 CPUs), ~2.7GHz","location":"REPAIR","department":"PCBA","user_pic":"REPAIR","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (305, 1, 'AST-PC-PCBA-0038', '{"pc_name":"Dell","ip_address":"10.0.2.62","mac_address":"E4-54-E8-DB-51-9D","brand":"Dell","serial_number":"","processor":"Windows 7 Professional 64-bit","ram_gb":null,"storage_type":"HDD","storage_capacity":"","os_version":"Intel(R) Core(TM) i3-2120 CPU @ 3.30GHz (4 CPUs), ~3.3GHz","location":"SMT B - STAFF LOT TICKET","department":"PCBA","user_pic":"STAFF LOT TICKET","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (306, 1, 'AST-PC-PCBA-0039', '{"pc_name":"Dell","ip_address":"192.168.100.168","mac_address":"40-61-86-92-0B-BD","brand":"Dell","serial_number":"","processor":"Windows 7 Professional 64-bit","ram_gb":null,"storage_type":"HDD","storage_capacity":"","os_version":"n/a","location":"SMT B - STAFF RYOYO DENSO","department":"PCBA","user_pic":"STAFF RYOYO DENSO","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (307, 1, 'AST-PC-PCBA-0040', '{"pc_name":"HP","ip_address":"192.168.100.136","mac_address":"?78-AC-C0-B7-D0-7C","brand":"HP","serial_number":"","processor":"Windows 7 Professional 64-bit","ram_gb":null,"storage_type":"HDD","storage_capacity":"512GB","os_version":"Intel(R) Core(TM) i5- 3470CPU @ 3.20GHz (4 CPUs), ~3.2GHz","location":"SMT B - STAFF (UNI DEVI)","department":"PCBA","user_pic":"STAFF (UNI DEVI)","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (308, 1, 'AST-PC-PCBA-0041', '{"pc_name":"Dell","ip_address":"10.0.2.251","mac_address":"9C-B6-54-EB-5F-7E","brand":"Dell","serial_number":"","processor":"Windows 10 Pro 64-bit","ram_gb":null,"storage_type":"HDD","storage_capacity":"256 GB","os_version":"Intel(R) Core(TM) i3-10105 CPU @ 3.70GHz (8 CPUs), ~3.7GHz","location":"SMT C - L18 Input","department":"PCBA","user_pic":"L18 Input","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (309, 1, 'AST-PC-PCBA-0042', '{"pc_name":"HP","ip_address":"10.0.1.10","mac_address":"90-FB-A6-0A-76-33","brand":"HP","serial_number":"","processor":"Windows 7 Professional 64-bit","ram_gb":null,"storage_type":"HDD","storage_capacity":"256 GB","os_version":"Intel(R) Core(TM) i3-2120 CPU @ 3.30GHz (4 CPUs), ~3.3GHz","location":"SMT C - L18 Output","department":"PCBA","user_pic":"L18 Output","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (310, 1, 'AST-PC-PCBA-0043', '{"pc_name":"Dell","ip_address":"10.0.2.112","mac_address":"00-21-86-FA-90-A4","brand":"Dell","serial_number":"","processor":"Windows 11 Pro 64-bit","ram_gb":null,"storage_type":"HDD","storage_capacity":"128 GB","os_version":"Intel(R) Core(TM) i3-10100 CPU @ 3.60GHz (8 CPUs), ~3.6GHz","location":"SMT C - L19 Input","department":"PCBA","user_pic":"L19 Input","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (311, 1, 'AST-PC-PCBA-0044', '{"pc_name":"Dell","ip_address":"10.0.2.28","mac_address":"18-66-DA-22-FC-C3","brand":"Dell","serial_number":"","processor":"Windows 10 Pro 64-bit","ram_gb":null,"storage_type":"HDD","storage_capacity":"128 GB","os_version":"Intel(R) Core(TM) i3-10105 CPU @ 3.70GHz (8 CPUs), ~3.7GHz","location":"SMT C - L19 Output","department":"PCBA","user_pic":"L19 Output","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (312, 1, 'AST-PC-PCBA-0045', '{"pc_name":"Dell","ip_address":"10.0.2.98","mac_address":"?B8-AC-6F-20-E6-AC","brand":"Dell","serial_number":"","processor":"Windows 10 Pro 64-bit","ram_gb":null,"storage_type":"HDD","storage_capacity":"256 GB","os_version":"Intel(R) Core(TM) i3-10105 CPU @ 3.70GHz (8 CPUs), ~3.7GHz","location":"SMT C - L20 Input","department":"PCBA","user_pic":"L20 Input","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (313, 1, 'AST-PC-PCBA-0046', '{"pc_name":"Lenovo","ip_address":"10.0.2.5","mac_address":"?00-1D-60-2D-CD-50","brand":"Lenovo","serial_number":"","processor":"Windows 10 Pro 64-bit","ram_gb":null,"storage_type":"HDD","storage_capacity":"128 GB","os_version":"Intel(R) Core(TM) i5 CPU 750  @ 2.67GHz (4 CPUs), ~2.7GHz","location":"SMT C - L20 Output","department":"PCBA","user_pic":"L20 Output","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (314, 1, 'AST-PC-PCBA-0047', '{"pc_name":"Dell","ip_address":"10.0.2.122","mac_address":"?E8-39-35-5F-27-18","brand":"Dell","serial_number":"","processor":"Windows 10 Home 64-bit","ram_gb":null,"storage_type":"HDD","storage_capacity":"128 GB","os_version":"Intel(R) Core(TM) i3-10105 CPU @ 3.70GHz (8 CPUs), ~3.7GHz","location":"SMT C - L21 Input","department":"PCBA","user_pic":"L21 Input","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (315, 1, 'AST-PC-PCBA-0048', '{"pc_name":"Lenovo","ip_address":"10.0.2.218","mac_address":"44-8A-5B-09-FA-4B","brand":"Lenovo","serial_number":"","processor":"Windows 10 Pro 64-bit","ram_gb":null,"storage_type":"HDD","storage_capacity":"128 GB","os_version":"Intel(R) Core(TM) i5 CPU 750  @ 2.67GHz (4 CPUs), ~2.7GHz","location":"SMT C - L21 Ouput","department":"PCBA","user_pic":"L21 Ouput","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (316, 1, 'AST-PC-PCBA-0049', '{"pc_name":"Dell","ip_address":"192.168.50.3","mac_address":"00-25-64-BE-D1-1E","brand":"Dell","serial_number":"","processor":"Windows 10 Pro 64-bit","ram_gb":null,"storage_type":"HDD","storage_capacity":"256 GB","os_version":"Intel(R) Core(TM) i3-10105 CPU @ 3.70GHz (8 CPUs), ~3.7GHz","location":"SMT C - L22 Input","department":"PCBA","user_pic":"L22 Input","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (317, 1, 'AST-PC-PCBA-0050', '{"pc_name":"HP","ip_address":"10.0.2.103","mac_address":"2C-44-FD-28-7E-B9","brand":"HP","serial_number":"","processor":"Windows 10 Home 64-bit","ram_gb":null,"storage_type":"HDD","storage_capacity":"512 GB","os_version":"Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz (4 CPUs), ~3.1GHz","location":"SMT C - L22 Output","department":"PCBA","user_pic":"L22 Output","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (318, 1, 'AST-PC-PCBA-0051', '{"pc_name":"HP","ip_address":"1192.168.1.187","mac_address":"78-AC-C0-BA-45-24","brand":"HP","serial_number":"","processor":"Windows 10 Pro 64-bit","ram_gb":null,"storage_type":"HDD","storage_capacity":"512 GB","os_version":"Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz (4 CPUs), ~3.1GHz","location":"SMT C - L23 Input","department":"PCBA","user_pic":"L23 Input","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (319, 1, 'AST-PC-PCBA-0052', '{"pc_name":"Acer","ip_address":"192.168.100.158","mac_address":"80-C1-6E-F0-FB-7E","brand":"Acer","serial_number":"","processor":"Windows 10 Pro 64-bit","ram_gb":null,"storage_type":"HDD","storage_capacity":"256 GB","os_version":"Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz (4 CPUs), ~3.1GHz","location":"SMT C - L23 Output","department":"PCBA","user_pic":"L23 Output","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (320, 1, 'AST-PC-PCBA-0053', '{"pc_name":"EPSON","ip_address":"10.0.2.88","mac_address":"70-20-84-05-2B-A4","brand":"EPSON","serial_number":"","processor":"Windows 7 Professional 64-bit","ram_gb":null,"storage_type":"HDD","storage_capacity":"256 GB","os_version":"Intel(R) Celeron(R) CPU 430  @ 1.80GHz, ~1.8GHz","location":"SMT C - PC Staff Niken","department":"PCBA","user_pic":"PC Staff Niken","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (321, 1, 'AST-PC-PCBA-0054', '{"pc_name":"Dell","ip_address":"10.0.2.26","mac_address":"70-20-84-08-35-04","brand":"Dell","serial_number":"","processor":"Windows 7 Professional 64-bit","ram_gb":null,"storage_type":"HDD","storage_capacity":"512 GB","os_version":"Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 CPUs), ~3.3GHz","location":"SMT C - PC Staff Fitri","department":"PCBA","user_pic":"PC Staff Fitri","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (322, 1, 'AST-PC-PCBA-0055', '{"pc_name":"Lenovo","ip_address":"192.168.13.121","mac_address":"C8-9C-DC-3C-0E-18","brand":"Lenovo","serial_number":"","processor":"Windows 7 Professional 32-bit","ram_gb":null,"storage_type":"HDD","storage_capacity":"128 GB","os_version":"Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz (4 CPUs), ~3.1GHz","location":"SMT C - PC Staff Uda Juna","department":"PCBA","user_pic":"PC Staff Uda Juna","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (323, 1, 'AST-PC-PCBA-0056', '{"pc_name":"Hewlett","ip_address":"10.0.2.123","mac_address":"64-00-6A-51-F0-F3","brand":"Hewlett","serial_number":"","processor":"","ram_gb":null,"storage_type":"HDD","storage_capacity":"128 GB","os_version":"Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz (4 CPUs), ~3.1GHz","location":"SMT C - PC Staff MH","department":"PCBA","user_pic":"PC Staff MH","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (324, 1, 'AST-PC-PCBA-0057', '{"pc_name":"Dell","ip_address":"10.0.2.213","mac_address":"70-B5-E8-33-2C-27","brand":"Dell","serial_number":"","processor":"","ram_gb":null,"storage_type":"HDD","storage_capacity":"128 GB","os_version":"Intel(R) Core(TM) i3-9100 CPU @ 3.60GHz (4 CPUs), ~3.6GHz","location":"SMT C - PC Staff Display","department":"PCBA","user_pic":"PC Staff Display","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (325, 1, 'AST-PC-PCBA-0058', '{"pc_name":"Hewlett","ip_address":"192.168.0.100","mac_address":"D4-BE-D9-D7-B0-64","brand":"Hewlett","serial_number":"","processor":"","ram_gb":null,"storage_type":"HDD","storage_capacity":"","os_version":"","location":"SMT C - PC QC Staff FG Area","department":"PCBA","user_pic":"PC QC Staff FG Area","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (326, 1, 'AST-PC-PCBA-0059', '{"pc_name":"Dell","ip_address":"192.168.0.101","mac_address":"74-27-EA-52-D4-F1","brand":"Dell","serial_number":"","processor":"","ram_gb":null,"storage_type":"HDD","storage_capacity":"","os_version":"","location":"SMT C - PC QC Grooming FG Area","department":"PCBA","user_pic":"PC QC Grooming FG Area","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (327, 1, 'AST-PC-PCBA-0060', '{"pc_name":"DELL","ip_address":"192.168.10.24","mac_address":"18-66-DA-03-E1-36","brand":"DELL","serial_number":"","processor":"","ram_gb":null,"storage_type":"HDD","storage_capacity":"128 GB","os_version":"Intel(R) Core(TM) i3-10105 CPU @ 3.70GHz (8 CPUs), ~3.7GHz","location":"SMT C - DGS Lane 23","department":"PCBA","user_pic":"DGS Lane 23","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (328, 1, 'AST-PC-PCBA-0061', '{"pc_name":"DELL","ip_address":"192.168.10.25","mac_address":"30-9C-23-F9-5D-81","brand":"DELL","serial_number":"","processor":"","ram_gb":null,"storage_type":"HDD","storage_capacity":"256 GB","os_version":"Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz (12 CPUs)","location":"SMT C - DGS Lane 22","department":"PCBA","user_pic":"DGS Lane 22","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (329, 1, 'AST-PC-PCBA-0062', '{"pc_name":"DELL","ip_address":"192.168.10.20","mac_address":"00-C1-6E-E0-07-DD","brand":"DELL","serial_number":"","processor":"","ram_gb":null,"storage_type":"HDD","storage_capacity":"256 GB","os_version":"Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz (12 CPUs)","location":"SMT C - DGS Lane 21","department":"PCBA","user_pic":"DGS Lane 21","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (330, 1, 'AST-PC-PCBA-0063', '{"pc_name":"DELL","ip_address":"192.168.10.2","mac_address":"70-71-BC-CD-25-85","brand":"DELL","serial_number":"","processor":"","ram_gb":null,"storage_type":"HDD","storage_capacity":"256 GB","os_version":"Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz (12 CPUs)","location":"SMT C - DGS Lane 20","department":"PCBA","user_pic":"DGS Lane 20","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (331, 1, 'AST-PC-PCBA-0064', '{"pc_name":"Lenovo","ip_address":"192.168.10.3","mac_address":"34-64-A9-DE-1B-7D","brand":"Lenovo","serial_number":"","processor":"","ram_gb":null,"storage_type":"HDD","storage_capacity":"256 GB","os_version":"Intel(R) Pentium(R) Gold G6400 CPU @ 4.00GHz (4 CPUs), ~4.0GHz","location":"SMT C - DGS Lane 19","department":"PCBA","user_pic":"DGS Lane 19","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (332, 1, 'AST-PC-PCBA-0065', '{"pc_name":"Lenovo","ip_address":"192.168.10.2","mac_address":"","brand":"Lenovo","serial_number":"","processor":"","ram_gb":null,"storage_type":"HDD","storage_capacity":"256 GB","os_version":"Intel(R) Pentium(R) Gold G6400 CPU @ 4.00GHz (4 CPUs), ~4.0GHz","location":"SMT C - DGS LANE 18","department":"PCBA","user_pic":"DGS LANE 18","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (333, 1, 'AST-PC-PCBA-0066', '{"pc_name":"Dell","ip_address":"10.0.2.161","mac_address":"","brand":"Dell","serial_number":"","processor":"","ram_gb":null,"storage_type":"HDD","storage_capacity":"1 TB","os_version":"Intel(R) Core(TM) i3-10105 CPU @ 3.70GHz (8 CPUs), ~3.7GHz","location":"SMT C - Porticos Visual","department":"PCBA","user_pic":"Porticos Visual","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (334, 1, 'AST-PC-PCBA-0067', '{"pc_name":"Dell","ip_address":"10.0.2.215","mac_address":"","brand":"Dell","serial_number":"","processor":"","ram_gb":null,"storage_type":"HDD","storage_capacity":"512 GB","os_version":"Intel(R) Core(TM) i3-9100 CPU @ 3.60GHz (4 CPUs), ~3.6GHz","location":"SMT C - Porticos Apply Label","department":"PCBA","user_pic":"Porticos Apply Label","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (335, 1, 'AST-PC-PCBA-0068', '{"pc_name":"Dell","ip_address":"10.0.2.253","mac_address":"","brand":"Dell","serial_number":"","processor":"","ram_gb":null,"storage_type":"HDD","storage_capacity":"1TB","os_version":"12th Gen Intel(R) Core(TM) i3-12100 (8 CPUs), ~3.3GHz","location":"SMT C - Porticos EOL Jig 1","department":"PCBA","user_pic":"Porticos EOL Jig 1","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (336, 1, 'AST-PC-PCBA-0069', '{"pc_name":"LENOVO","ip_address":"192.168.10.147","mac_address":"","brand":"LENOVO","serial_number":"","processor":"","ram_gb":null,"storage_type":"HDD","storage_capacity":"512 GB","os_version":"Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz (4 CPUs), ~3.5GHz","location":"SMT C - ESD","department":"PCBA","user_pic":"ESD","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (337, 1, 'AST-PC-PCBA-0070', '{"pc_name":"Dell","ip_address":"192.168.0.103","mac_address":"","brand":"Dell","serial_number":"","processor":"","ram_gb":null,"storage_type":"HDD","storage_capacity":"128 GB","os_version":"Intel(R) Core(TM) i3-10100 CPU @ 3.60GHz (8 CPUs), ~3.6GHz","location":"SMT C - TV MONITORING","department":"PCBA","user_pic":"TV MONITORING","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (338, 1, 'AST-PC-PCBA-0071', '{"pc_name":"Dell","ip_address":"10.0.2.175","mac_address":"","brand":"Dell","serial_number":"","processor":"","ram_gb":null,"storage_type":"HDD","storage_capacity":"512GB","os_version":"Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz (4 CPUs), ~3.1GHz","location":"SMT C - Porticos Assembly","department":"PCBA","user_pic":"Porticos Assembly","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (339, 1, 'AST-PC-PCBA-0072', '{"pc_name":"Dell","ip_address":"10.0.2.54","mac_address":"","brand":"Dell","serial_number":"","processor":"","ram_gb":null,"storage_type":"HDD","storage_capacity":"1TB","os_version":"Intel(R) Core(TM) i3-9100 CPU @ 3.60GHz","location":"SMT C - Repair","department":"PCBA","user_pic":"Repair","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (340, 1, 'AST-PC-PCBA-0073', '{"pc_name":"Endeavor","ip_address":"192.168.13.64","mac_address":"","brand":"Endeavor","serial_number":"","processor":"","ram_gb":null,"storage_type":"HDD","storage_capacity":"256GB","os_version":"Intel(R) Celeron(R) D CPU 3.06GHz, ~3.1GHz","location":"SMT C - QC Leader","department":"PCBA","user_pic":"QC Leader","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (341, 1, 'AST-PC-PCBA-0074', '{"pc_name":"Endeavor","ip_address":"192.168.100.139","mac_address":"","brand":"Endeavor","serial_number":"","processor":"","ram_gb":null,"storage_type":"HDD","storage_capacity":"1TB","os_version":"Intel(R) Core(TM) i3-9100 CPU @ 3.60GHz (4 CPUs), ~3.6GHz","location":"SMT C - QC Roima","department":"PCBA","user_pic":"QC Roima","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (342, 1, 'AST-PC-PCBA-0075', '{"pc_name":"ThinkCentre","ip_address":"10.0.1.92","mac_address":"","brand":"ThinkCentre","serial_number":"","processor":"","ram_gb":null,"storage_type":"HDD","storage_capacity":"512GB","os_version":"Intel(R) Pentium(R) CPU G4400 @ 3.30GHz (2 CPUs), ~3.3GHz","location":"SMT C - Staff QC","department":"PCBA","user_pic":"Staff QC","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (343, 1, 'AST-PC-PCBA-0076', '{"pc_name":"HP","ip_address":"10.0.2.163","mac_address":"","brand":"HP","serial_number":"","processor":"","ram_gb":null,"storage_type":"HDD","storage_capacity":"256GB","os_version":"Intel(R) Core(TM) 2 Duo CPU E7300 (2 CPU) 2.70GHz","location":"SMT C -  OQC","department":"PCBA","user_pic":"OQC","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (344, 1, 'AST-PC-PCBA-0077', '{"pc_name":"Dell","ip_address":"192.168.13.48","mac_address":"","brand":"Dell","serial_number":"","processor":"","ram_gb":null,"storage_type":"HDD","storage_capacity":"256GB","os_version":"Intel(R) Core(TM)2 Duo CPU     E8400  @ 3.00GHz (2 CPUs), ~3.0GHz","location":"PMC 2A - PC ISSUEING / UPDATE SECOEND LOT","department":"PCBA","user_pic":"PMC 2A - PC ISSUEING / UPDATE SECOEND LOT","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (345, 1, 'AST-PC-PCBA-0078', '{"pc_name":"Dell","ip_address":"192.168.0.178","mac_address":"","brand":"Dell","serial_number":"","processor":"","ram_gb":null,"storage_type":"HDD","storage_capacity":"128 GB","os_version":"Intel(R) Core(TM) i3-9100 CPU @ 3.60GHz (4 CPUs), ~3.6GHz","location":"PMC 3 - PC ISSUEING BLUEETI","department":"PCBA","user_pic":"PC ISSUEING BLUEETI","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (346, 1, 'AST-PC-PCBA-0079', '{"pc_name":"HP","ip_address":"192.168.13.23","mac_address":"","brand":"HP","serial_number":"","processor":"","ram_gb":null,"storage_type":"HDD","storage_capacity":"256GB","os_version":"Intel(R) Core(TM) i5 CPU         650  @ 3.20GHz (4 CPUs), ~3.2GHz","location":"PMC 3 - PC ISSUEING EPSON,RYOYO, DENSO","department":"PCBA","user_pic":"PC ISSUEING EPSON,RYOYO, DENSO","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (347, 1, 'AST-PC-PCBA-0080', '{"pc_name":"HP","ip_address":"192.168.0.190","mac_address":"","brand":"HP","serial_number":"","processor":"","ram_gb":null,"storage_type":"HDD","storage_capacity":"256GB","os_version":"Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz (4 CPUs), ~3.3GHz","location":"PMC 3 - PC ISSUEING BLUEETI","department":"PCBA","user_pic":"PC ISSUEING BLUEETI","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (348, 1, 'AST-PC-PCBA-0081', '{"pc_name":"HP","ip_address":"10.0.2.187","mac_address":"","brand":"HP","serial_number":"","processor":"","ram_gb":null,"storage_type":"HDD","storage_capacity":"128 GB","os_version":"Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 CPUs), ~3.2GHz","location":"PMC 3 - PC STAFF (BANG ANDI)","department":"PCBA","user_pic":"PC STAFF (BANG ANDI)","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (349, 1, 'AST-PC-PCBA-0082', '{"pc_name":"LENOVO","ip_address":"192.168.100.172","mac_address":"","brand":"LENOVO","serial_number":"","processor":"","ram_gb":null,"storage_type":"HDD","storage_capacity":"128 GB","os_version":"Intel(R) Core(TM)2 Quad CPU    Q8300  @ 2.50GHz (4 CPUs), ~2.5GHz","location":"PMC 3 - PC STAFF (BANG JAKA)","department":"PCBA","user_pic":"PC STAFF (BANG JAKA)","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (350, 1, 'AST-PC-PCBA-0083', '{"pc_name":"LENOVO","ip_address":"192.168.100.170","mac_address":"","brand":"LENOVO","serial_number":"","processor":"","ram_gb":null,"storage_type":"HDD","storage_capacity":"128 GB","os_version":"Intel(R) Core(TM) i5 CPU         750  @ 2.67GHz (4 CPUs), ~2.7GHz","location":"PMC 3 - PC STAFF (BANG RIFKI)","department":"PCBA","user_pic":"PC STAFF (BANG RIFKI)","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (351, 1, 'AST-PC-PCBA-0084', '{"pc_name":"Dell","ip_address":"10.0.1.73","mac_address":"","brand":"Dell","serial_number":"","processor":"","ram_gb":null,"storage_type":"HDD","storage_capacity":"512GB","os_version":"Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz (4 CPUs), ~3.3GHz","location":"PMC 3 - PC STAFF (BANG JOHAN)","department":"PCBA","user_pic":"PC STAFF (BANG JOHAN)","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (352, 1, 'AST-PC-PCBA-0085', '{"pc_name":"Dell","ip_address":"10.0.2.16","mac_address":"","brand":"Dell","serial_number":"","processor":"","ram_gb":null,"storage_type":"HDD","storage_capacity":"256GB","os_version":"Intel(R) Core(TM)2 Duo CPU     E7500  @ 2.93GHz (2 CPUs), ~2.9GHz","location":"PMC 1 - PC STAFF PMC 1","department":"PCBA","user_pic":"PC STAFF PMC 1","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (353, 1, 'AST-PC-PCBA-0086', '{"pc_name":"EPSON","ip_address":"10.0.2.48","mac_address":"","brand":"EPSON","serial_number":"","processor":"","ram_gb":null,"storage_type":"HDD","storage_capacity":"256GB","os_version":"Intel(R) Celeron(R) CPU          430  @ 1.80GHz, ~1.8GHz","location":"PMC 1 - PC STAFF PMC 1","department":"PCBA","user_pic":"PC STAFF PMC 1","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (354, 1, 'AST-PC-PCBA-0087', '{"pc_name":"HP","ip_address":"10.0.2.97","mac_address":"","brand":"HP","serial_number":"","processor":"","ram_gb":null,"storage_type":"HDD","storage_capacity":"512 GB","os_version":"Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz (4 CPUs), ~3.1GHz","location":"PMC 1 - PC STAFF PMC 1","department":"PCBA","user_pic":"PC STAFF PMC 1","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (355, 1, 'AST-PC-PCBA-0088', '{"pc_name":"LENOVO","ip_address":"10.0.2.117","mac_address":"","brand":"LENOVO","serial_number":"","processor":"","ram_gb":null,"storage_type":"HDD","storage_capacity":"256GB","os_version":"Intel(R) Core(TM) i5-4570S CPU @ 2.90GHz (4 CPUs), ~2.9GHz","location":"PMC 1 - PC STAFF PMC 1","department":"PCBA","user_pic":"PC STAFF PMC 1","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (356, 1, 'AST-PC-PCBA-0089', '{"pc_name":"Dell","ip_address":"192.168.100.171","mac_address":"","brand":"Dell","serial_number":"","processor":"","ram_gb":null,"storage_type":"HDD","storage_capacity":"512GB","os_version":"Intel(R) Core(TM)2 Duo CPU     E7500  @ 2.93GHz (2 CPUs), ~2.9GHz","location":"PMC 6 - PC LUAR","department":"PCBA","user_pic":"PC LUAR","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (357, 1, 'AST-PC-PCBA-0090', '{"pc_name":"HP","ip_address":"10.0.2.13","mac_address":"","brand":"HP","serial_number":"","processor":"","ram_gb":null,"storage_type":"HDD","storage_capacity":"512GB","os_version":"Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 CPUs), ~3.2GHz","location":"PMC 6 - PC TRIYA","department":"PCBA","user_pic":"PC TRIYA","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (358, 1, 'AST-PC-PCBA-0091', '{"pc_name":"HP","ip_address":"10.0.1.4","mac_address":"","brand":"HP","serial_number":"","processor":"","ram_gb":null,"storage_type":"HDD","storage_capacity":"300GB","os_version":"Intel(R) Core(TM) i3-2120 CPU @ 3.30GHz (4 CPUs), ~3.3GHz","location":"PMC 6 - PC KIRI TRIYA","department":"PCBA","user_pic":"PC KIRI TRIYA","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (359, 1, 'AST-PC-PCBA-0092', '{"pc_name":"HP","ip_address":"10.0.1.7","mac_address":"","brand":"HP","serial_number":"","processor":"","ram_gb":null,"storage_type":"HDD","storage_capacity":"512GB","os_version":"Intel(R) Core(TM) i3-2120 CPU @ 3.30GHz (4 CPUs), ~3.3GHz","location":"PMC 6 - PC MASTER PRINTER 1","department":"PCBA","user_pic":"PC MASTER PRINTER 1","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (360, 1, 'AST-PC-PCBA-0093', '{"pc_name":"LENOVO","ip_address":"10.0.1.47","mac_address":"","brand":"LENOVO","serial_number":"","processor":"","ram_gb":null,"storage_type":"HDD","storage_capacity":"512GB","os_version":"Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 CPUs), ~3.2GHz","location":"PMC 6 - PC PMC LASCAR, CORINTECH","department":"PCBA","user_pic":"PC PMC LASCAR, CORINTECH","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (361, 1, 'AST-PC-PCBA-0094', '{"pc_name":"LENOVO","ip_address":"10.0.1.46","mac_address":"","brand":"LENOVO","serial_number":"","processor":"","ram_gb":null,"storage_type":"HDD","storage_capacity":"512GB","os_version":"Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 CPUs), ~3.2GHz","location":"PMC 6 - PC REGINA","department":"PCBA","user_pic":"PC REGINA","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (362, 1, 'AST-PC-PCBA-0095', '{"pc_name":"LENOVO","ip_address":"192.168.0.113","mac_address":"","brand":"LENOVO","serial_number":"","processor":"","ram_gb":null,"storage_type":"HDD","storage_capacity":"512GB","os_version":"Intel(R) Core(TM) i5 CPU         650  @ 3.20GHz (4 CPUs), ~3.2GHz","location":"PMC 6 - PC MARLINA","department":"PCBA","user_pic":"PC MARLINA","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (363, 1, 'AST-PC-PCBA-0096', '{"pc_name":"Dell","ip_address":"10.0.2.25","mac_address":"","brand":"Dell","serial_number":"","processor":"","ram_gb":null,"storage_type":"HDD","storage_capacity":"512GB","os_version":"n/a","location":"PMC 6 - PC SEBELAH PC FAHMI","department":"PCBA","user_pic":"PC SEBELAH PC FAHMI","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (364, 1, 'AST-PC-PCBA-0097', '{"pc_name":"Dell","ip_address":"10.0.2.53","mac_address":"","brand":"Dell","serial_number":"","processor":"","ram_gb":null,"storage_type":"HDD","storage_capacity":"128GB","os_version":"Intel(R) Core(TM) i3-9100 CPU @ 3.60GHz (4 CPUs), ~3.6GHz","location":"PMC 6 - PC FAHMI","department":"PCBA","user_pic":"PC FAHMI","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (365, 1, 'AST-PC-PCBA-0098', '{"pc_name":"Dell","ip_address":"192.168.0.108","mac_address":"","brand":"Dell","serial_number":"","processor":"","ram_gb":null,"storage_type":"HDD","storage_capacity":"512GB","os_version":"n/a","location":"PMC 6 - PC NANIK","department":"PCBA","user_pic":"PC NANIK","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (366, 1, 'AST-PC-PCBA-0099', '{"pc_name":"Acer","ip_address":"10.0.2.197","mac_address":"","brand":"Acer","serial_number":"","processor":"","ram_gb":null,"storage_type":"HDD","storage_capacity":"512GB","os_version":"Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz (4 CPUs), ~3.2GHz","location":"PMC 6 - PC DI JENDELA AMBIL PART KIRI","department":"PCBA","user_pic":"PC DI JENDELA AMBIL PART KIRI","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (367, 1, 'AST-PC-PCBA-0100', '{"pc_name":"Dell","ip_address":"10.0.2.11","mac_address":"","brand":"Dell","serial_number":"","processor":"","ram_gb":null,"storage_type":"HDD","storage_capacity":"128GB","os_version":"Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 CPUs), ~3.3GHz","location":"PMC 6 - PC DI JENDELA AMBIL PART KANAN","department":"PCBA","user_pic":"PC DI JENDELA AMBIL PART KANAN","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (368, 1, 'AST-PC-PCBA-0101', '{"pc_name":"LENOVO","ip_address":"10.0.1.87","mac_address":"","brand":"LENOVO","serial_number":"","processor":"","ram_gb":null,"storage_type":"HDD","storage_capacity":"128GB","os_version":"Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 CPUs), ~3.2GHz","location":"PMC 6 - PC DI JENDELA AMBIL PART UJUNG","department":"PCBA","user_pic":"PC DI JENDELA AMBIL PART UJUNG","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (369, 1, 'AST-PC-PCBA-0102', '{"pc_name":"HP","ip_address":"192.168.13.22","mac_address":"","brand":"HP","serial_number":"","processor":"","ram_gb":null,"storage_type":"HDD","storage_capacity":"512GB","os_version":"Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz (4 CPUs), ~3.1GHz","location":"PMC - 4","department":"PCBA","user_pic":"PMC - 4","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (370, 1, 'AST-PC-PCBA-0103', '{"pc_name":"EPSON","ip_address":"10.0.2.90","mac_address":"","brand":"EPSON","serial_number":"","processor":"","ram_gb":null,"storage_type":"HDD","storage_capacity":"256GB","os_version":"Intel(R) Celeron(R) CPU          430  @ 1.80GHz, ~1.8GHz","location":"DENSO - PC VISUAL","department":"PCBA","user_pic":"DENSO - PC VISUAL","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');
INSERT INTO `hardware_items` (`id`, `category_id`, `asset_number`, `data`, `status`, `condition`, `created_at`, `updated_at`) VALUES (371, 1, 'AST-PC-PCBA-0104', '{"pc_name":"HP","ip_address":"192.168.9.11","mac_address":"","brand":"HP","serial_number":"","processor":"","ram_gb":null,"storage_type":"HDD","storage_capacity":"512 GB","os_version":"Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz (4 CPUs), ~3.5GHz","location":"DENSO - PC FLASH PROGRAM","department":"PCBA","user_pic":"DENSO - PC FLASH PROGRAM","purchase_date":"","warranty_expiry":"","supplier":"","purchase_price":null,"notes":""}', 'active', 'good', '2026-03-11 05:01:24', '2026-03-11 05:01:24');

-- departments (14 rows)
INSERT INTO `departments` (`id`, `name`, `created_at`) VALUES (1, 'PMC 3', '2026-03-11 03:45:42');
INSERT INTO `departments` (`id`, `name`, `created_at`) VALUES (2, 'FinishedGoods', '2026-03-11 03:45:42');
INSERT INTO `departments` (`id`, `name`, `created_at`) VALUES (3, 'SMT 3', '2026-03-11 03:45:42');
INSERT INTO `departments` (`id`, `name`, `created_at`) VALUES (4, 'Technician', '2026-03-11 03:45:42');
INSERT INTO `departments` (`id`, `name`, `created_at`) VALUES (5, 'IT PCBA', '2026-03-11 03:45:42');
INSERT INTO `departments` (`id`, `name`, `created_at`) VALUES (6, 'Engineering', '2026-03-11 03:45:42');
INSERT INTO `departments` (`id`, `name`, `created_at`) VALUES (7, 'QA', '2026-03-11 03:45:42');
INSERT INTO `departments` (`id`, `name`, `created_at`) VALUES (8, 'OHC', '2026-03-11 03:45:42');
INSERT INTO `departments` (`id`, `name`, `created_at`) VALUES (9, 'PMC 5', '2026-03-11 03:45:42');
INSERT INTO `departments` (`id`, `name`, `created_at`) VALUES (10, 'PMC 6', '2026-03-11 03:45:42');
INSERT INTO `departments` (`id`, `name`, `created_at`) VALUES (11, 'SMT 1', '2026-03-11 03:45:42');
INSERT INTO `departments` (`id`, `name`, `created_at`) VALUES (12, 'PMC 1', '2026-03-11 03:45:42');
INSERT INTO `departments` (`id`, `name`, `created_at`) VALUES (13, 'SMT 2', '2026-03-11 03:45:42');
INSERT INTO `departments` (`id`, `name`, `created_at`) VALUES (131, 'PCBA', '2026-03-13 07:29:20');

-- maintenance_schedules: empty

-- equipment_requests: empty

-- activity_logs (10 rows)
INSERT INTO `activity_logs` (`id`, `action`, `entity_type`, `entity_id`, `entity_name`, `details`, `user_name`, `created_at`) VALUES (3, 'delete', 'request', 3, 'REQ-20260314-001', '{"requester":"test"}', 'System', '2026-03-16 04:57:42');
INSERT INTO `activity_logs` (`id`, `action`, `entity_type`, `entity_id`, `entity_name`, `details`, `user_name`, `created_at`) VALUES (4, 'delete', 'request', 3, 'Request #3', '{"requester":""}', 'System', '2026-03-16 04:57:42');
INSERT INTO `activity_logs` (`id`, `action`, `entity_type`, `entity_id`, `entity_name`, `details`, `user_name`, `created_at`) VALUES (5, 'create', 'request', 4, 'REQ-20260316-001', '{"requester":"Test","priority":"normal"}', 'Test', '2026-03-16 04:58:10');
INSERT INTO `activity_logs` (`id`, `action`, `entity_type`, `entity_id`, `entity_name`, `details`, `user_name`, `created_at`) VALUES (6, 'status_change', 'hardware', 268, 'AST-PC-PCBA-0001', '{"asset_number":"AST-PC-PCBA-0001","from":"maintenance","to":"active"}', 'System', '2026-03-16 04:59:15');
INSERT INTO `activity_logs` (`id`, `action`, `entity_type`, `entity_id`, `entity_name`, `details`, `user_name`, `created_at`) VALUES (7, 'update', 'hardware', 268, 'AST-PC-PCBA-0001', '{"asset_number":"AST-PC-PCBA-0001"}', 'System', '2026-03-16 04:59:29');
INSERT INTO `activity_logs` (`id`, `action`, `entity_type`, `entity_id`, `entity_name`, `details`, `user_name`, `created_at`) VALUES (8, 'update', 'hardware', 268, 'AST-PC-PCBA-0001', '{"asset_number":"AST-PC-PCBA-0001"}', 'System', '2026-03-16 05:00:27');
INSERT INTO `activity_logs` (`id`, `action`, `entity_type`, `entity_id`, `entity_name`, `details`, `user_name`, `created_at`) VALUES (9, 'update', 'hardware', 268, 'AST-PC-PCBA-0001', '{"asset_number":"AST-PC-PCBA-0001"}', 'System', '2026-03-16 05:00:33');
INSERT INTO `activity_logs` (`id`, `action`, `entity_type`, `entity_id`, `entity_name`, `details`, `user_name`, `created_at`) VALUES (10, 'status_change', 'hardware', 268, 'AST-PC-PCBA-0001', '{"asset_number":"AST-PC-PCBA-0001","from":"active","to":"maintenance"}', 'System', '2026-03-16 05:03:13');
INSERT INTO `activity_logs` (`id`, `action`, `entity_type`, `entity_id`, `entity_name`, `details`, `user_name`, `created_at`) VALUES (11, 'status_change', 'hardware', 268, 'AST-PC-PCBA-0001', '{"asset_number":"AST-PC-PCBA-0001","from":"maintenance","to":"active"}', 'System', '2026-03-16 05:03:33');
INSERT INTO `activity_logs` (`id`, `action`, `entity_type`, `entity_id`, `entity_name`, `details`, `user_name`, `created_at`) VALUES (17, 'delete', 'request', 4, 'REQ-20260316-001', '{"requester":"Test"}', 'System', '2026-03-15 05:15:02');

-- notifications (4 rows)
INSERT INTO `notifications` (`id`, `type`, `title`, `message`, `entity_type`, `entity_id`, `is_read`, `priority`, `created_at`) VALUES (15, 'request_pending', 'New Equipment Request', 'Test submitted request REQ-20260316-001', 'request', 4, 1, 'normal', '2026-03-16 04:59:58');
INSERT INTO `notifications` (`id`, `type`, `title`, `message`, `entity_type`, `entity_id`, `is_read`, `priority`, `created_at`) VALUES (16, 'hardware_condition', 'Hardware Needs Attention', 'AST-PC-PCBA-0001 (PC / Desktop) is in broken condition', 'hardware', 268, 1, 'urgent', '2026-03-16 04:59:58');
INSERT INTO `notifications` (`id`, `type`, `title`, `message`, `entity_type`, `entity_id`, `is_read`, `priority`, `created_at`) VALUES (19, 'repair_overdue', 'Hardware Repair Overdue', 'AST-PC-PCBA-0001 (PC / Desktop) has been in repair for 2 days', 'hardware', 268, 1, 'high', '2026-03-16 05:05:46');
INSERT INTO `notifications` (`id`, `type`, `title`, `message`, `entity_type`, `entity_id`, `is_read`, `priority`, `created_at`) VALUES (20, 'request_pending', 'New Equipment Request', 'Test submitted request REQ-20260316-001', 'request', 4, 1, 'normal', '2026-03-15 05:13:44');

-- ribbons: Error - no such table: ribbons

-- ribbon_consumption: Error - no such table: ribbon_consumption

SET FOREIGN_KEY_CHECKS = 1;
