import { NextResponse } from 'next/server';
import nodemailer from 'nodemailer';
import { getReportData } from '@/lib/getReportData';
import { generateDailyReport } from '@/lib/generateReport';

// Environment variables or passed arguments
const SMTP_HOST = process.env.SMTP_HOST || '113.212.160.10';
const SMTP_PORT = parseInt(process.env.SMTP_PORT || '465');
const SMTP_USER = process.env.SMTP_USER || 'traceability-system@giken.co.id';
const SMTP_PASS = process.env.SMTP_PASS || 'V^2#h@4)Q%7*p&8^D!4)r';

export async function POST(req: Request) {
  try {
    const today = new Date().toISOString().split('T')[0];
    const data = await getReportData(today);

    // Render the PDF in memory
    const doc = await generateDailyReport(data, today);
    const pdfBuffer = Buffer.from(doc.output('arraybuffer'));

    // Configure Nodemailer Transport
    const transporter = nodemailer.createTransport({
      host: SMTP_HOST,
      port: SMTP_PORT,
      secure: SMTP_PORT === 465, // true for 465, false for other ports
      auth: {
        user: SMTP_USER,
        pass: SMTP_PASS,
      },
      tls: {
        rejectUnauthorized: false
      }
    });

    // Construct the email body summarizing key metrics
    const htmlBody = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h2 style="color: #1e3a8a;">IT Operations Daily Report</h2>
        <p>Dear Team,</p>
        <p>Please find attached the automated daily report for <strong>${today}</strong>.</p>
        
        <h3 style="border-bottom: 2px solid #e2e8f0; padding-bottom: 5px;">Executive Summary</h3>
        <ul>
          <li><strong>Present Manpower:</strong> ${data.attendance.present}</li>
          <li><strong>Pending Leaf Requests:</strong> ${data.leaves.pending}</li>
          <li><strong>Active Overtime Requests:</strong> ${data.overtime.total}</li>
          <li><strong>Recent Tickets Created:</strong> ${data.tickets.totalCreatedToday}</li>
          <li><strong>Active Projects:</strong> ${data.projects.totalActive}</li>
        </ul>

        <p>Detailed metrics, task progression, and shift arrangements (06:30 Cut-off) are available in the attached PDF.</p>
        
        <p style="color: #64748b; font-size: 12px; margin-top: 30px;">
          This is an automated message generated by the IT PCBA Management System.<br/>
          Do not reply directly to this email.
        </p>
      </div>
    `;

    // Send the email
    const info = await transporter.sendMail({
      from: '"IT PCBA System" <' + SMTP_USER + '>',
      to: 'aditya@giken.co.id',
      subject: `IT Daily Report - ${today}`,
      html: htmlBody,
      attachments: [
        {
          filename: `IT_Daily_Report_${today}.pdf`,
          content: pdfBuffer,
          contentType: 'application/pdf',
        },
      ],
    });

    console.log('Message sent: %s', info.messageId);

    return NextResponse.json({ success: true, messageId: info.messageId });
  } catch (error: any) {
    console.error('Email Generation Error:', error);
    return NextResponse.json(
      { success: false, error: 'Failed to send report', details: error.message },
      { status: 500 }
    );
  }
}
